VOICE_GRADES: dict[str, str] = {
    "af_heart": "A",
    "af_bella": "A-",
    "af_nicole": "B-",
    "af_aoede": "C+",
    "af_kore": "C+",
    "af_sarah": "C+",
    "af_alloy": "C",
    "af_nova": "C",
    "af_sky": "C-",
    "af_jessica": "D",
    "af_river": "D",
    "am_fenrir": "C+",
    "am_michael": "C+",
    "am_puck": "C+",
    "am_echo": "D",
    "am_eric": "D",
    "am_liam": "D",
    "am_onyx": "D",
    "am_santa": "D-",
    "am_adam": "F+",
    "bf_emma": "B-",
    "bf_isabella": "C",
    "bf_alice": "D",
    "bf_lily": "D",
    "bm_fable": "C",
    "bm_george": "C",
    "bm_lewis": "D+",
    "bm_daniel": "D",
    "jf_alpha": "C+",
    "jf_gongitsune": "C",
    "jf_tebukuro": "C",
    "jf_nezumi": "C-",
    "jm_kumo": "C-",
    "zf_xiaobei": "D",
    "zf_xiaoni": "D",
    "zf_xiaoxiao": "D",
    "zf_xiaoyi": "D",
    "zm_yunjian": "D",
    "zm_yunxi": "D",
    "zm_yunxia": "D",
    "zm_yunyang": "D",
    "hf_alpha": "C",
    "hf_beta": "C",
    "hm_omega": "C",
    "hm_psi": "C",
    "if_sara": "C",
    "im_nicola": "C",
    "ff_siwis": "B-",
}

_GRADE_RANK: dict[str, int] = {
    "A+": 1,
    "A": 2,
    "A-": 3,
    "B+": 4,
    "B": 5,
    "B-": 6,
    "C+": 7,
    "C": 8,
    "C-": 9,
    "D+": 10,
    "D": 11,
    "D-": 12,
    "F+": 13,
    "F": 14,
}


def _grade_rank(voice: str) -> int:
    return _GRADE_RANK.get(VOICE_GRADES.get(voice, ""), 99)
